export interface ConditionDTO {
  condition: string
  targetStep: string
}

export interface FormTemplateDTO {
  id: number
  name: string
}

export interface BaseStepDTO {
  name: string
  stepType: "NOTIFY" | "APPROVAL" | "CONDITION"
  id?: number 
}

export interface ApprovalStepDTO extends BaseStepDTO {
  stepType: "APPROVAL"
  validatorRoles: string[]
  requiredApproval: string // ANY, ALL, or number
  formTemplate?: FormTemplateDTO
}

export interface NotifyStepDTO extends BaseStepDTO {
  stepType: "NOTIFY"
  recipients: string[] // List of emails
  message: string
}

export interface ConditionStepDTO extends BaseStepDTO {
  stepType: "CONDITION"
  condition: ConditionDTO[]
}

export type ProcessStepDTO = ApprovalStepDTO | NotifyStepDTO | ConditionStepDTO

export interface ProcessDefinitionDTO {
  id?: number // Optional as it will be generated by backend
  name: string
  formTemplate?: FormTemplateDTO
  steps: ProcessStepDTO[]
}
